[[ignition.1670764953]]
engine = ignition
Transform = 'ignition::{Transform, TransformTrait}'
Position = 'ignition::{Position, PositionTrait}'
Rotation = 'ignition::{Rotation, RotationTrait}'
Velocity = 'ignition::{Velocity, VelocityTrait}'
Number = 'ignition::life::{Number, NumberTrait}'
