[[ignition.1669481819]]
engine = ignition
Number = "ignition::{Number, NumberTrait}"
Transform = "ignition::{Transform, TransformTrait}"
Position = "ignition::{Position, PositionTrait}"
Rotation = "ignition::{Rotation, RotationTrait}"
Velocity = "ignition::{Velocity, VelocityTrait}"
Test = "ignition::life::{Test, TestTrait}"
